#!/usr/bin/env ruby
here = File.expand_path File.dirname __FILE__
$:<<here
require 'lib/github_flavored_markdown'
include GithubFlavoredMarkdown
ARGV.each do |arg|
  old_path = arg
  new_path = arg.gsub(/\.md$/, '.step')
  old = File.read(old_path)
  puts new_path
  File.open(new_path, "w") do |f|
    f.puts "div do"
    f.puts "note <<-MARKDOWN"
    f.write old.
      gsub(/^# (.*)$/, "  MARKDOWN\nend\n\nstep \"\\1\" do\n  note <<-MARKDOWN\n")
    f.puts "  MARKDOWN"
    f.puts "end"
  end
end
