#!/usr/bin/env ruby
here = File.expand_path File.dirname __FILE__
$:<<here
require 'lib/media_wiki'
include MediaWiki
ARGV.each do |arg|
  old_path = arg
  new_path = arg.gsub(/\.mw$/, '.md')
  old = File.read(old_path)
  File.open(new_path, "w") do |f|
    f.write mw2md(old)
  end
end
