#!/usr/bin/env ruby
here = File.expand_path File.dirname __FILE__
$:<<here
require 'lib/media_wiki'
include MediaWiki
ARGV.each do |arg|
  old_path = arg
  new_path = arg.gsub(/\.mw$/, '.step')
  old = File.read(old_path)
  puts new_path
  File.open(new_path, "w") do |f|
    f.puts "div do"
    f.puts "note <<-MARKDOWN"
    f.write mw2md(old).
      gsub(/^# (.*)$/, "  MARKDOWN\n  end\n\nstep \"\\1\" do\n  note <<-MARKDOWN\n")
    f.puts "  MARKDOWN"
    f.puts "end"
  end
end
